### ISSUE TITLE
Solidity compilation can sometimes fail with error about `isDevMode()`

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0-ethereum#26] opened 2024-02-29 17:18 UTC

**Comment by Cardosaum** [comment] 2024-03-05 17:23
This issue can happen in the definition of `devMode` ([source file](https://github.com/risc0/risc0-ethereum/blob/90d08442ac83170e94f7670e924bab27cefc6141/contracts/src/RiscZeroCheats.sol#L33-L38))

The current function signature is `function devMode() internal view returns (bool)`, a `view` function.
The problem arises by the fact that `forge` fails to compile the function complaining that this function can not be `view`, but we didn't see this compilation error in CI and it doesn't seem clear why this function should not be `view`.

It's not clear if the problem is a compiler version mismatch or something else.

**Comment by capossele** [comment] 2024-03-11 23:53
Fixed by #37

**Closed by capossele** 2024-03-11 23:53 UTC
